on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: 'Build & Release Android'
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          fetch-depth:  0

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release
      
      - name: Extract version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Generate Tag Name
        id: tag
        run: |
          TAG="v${VERSION}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            TAG="${TAG}-build-${GITHUB_RUN_NUMBER}"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          tag: ${{ env.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          makeLatest: true
          replacesArtifacts: true
